version: '3.5' # 或者使用你适用的Compose版本

services:
  kbrain:
    container_name: face-recog
    image: kbrain:6.3-dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    restart: always
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./:/opt/nvidia/deepstream/deepstream/sources/face-recognition-deepstream
    working_dir: /opt/nvidia/deepstream/deepstream/sources/face-recognition-deepstream
    command: tail -f /dev/null  
    network_mode: host 
    #stdin_open: true
    #tty: true
